import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

test('Windows launcher sincronizza dipendenze',()=>{const text=fs.readFileSync('RUN-WINDOWS.bat','utf8');assert.match(text,/npm install --no-audit --no-fund/i);assert.match(text,/_davCONVERT v26\.10\.3/);});
test('Vite preserva isolamento Tauri',()=>{const text=fs.readFileSync('vite.config.js','utf8');assert.match(text,/const host = process\.env\.TAURI_DEV_HOST/);assert.match(text,/src-tauri/);});
test('dipendenze conversione sono presenti',()=>{const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));assert.equal(pkg.dependencies['@tauri-apps/plugin-dialog'],'2');const cargo=fs.readFileSync('src-tauri/Cargo.toml','utf8');assert.match(cargo,/image = /);});
test('backend converte senza upload o rete',()=>{const text=fs.readFileSync('src-tauri/src/lib.rs','utf8');assert.match(text,/fn convert_file/);assert.doesNotMatch(text,/reqwest|http::|https:\/\//i);});
test('interfaccia include drag drop e design suite',()=>{const main=fs.readFileSync('src/main.js','utf8');assert.match(main,/onDragDropEvent/);assert.match(main,/Offrimi Un Caffè/);assert.doesNotMatch(main,/Comprami Un Caffè/);assert.match(main,/davstudios\.it/);const style=fs.readFileSync('src/styles.css','utf8');assert.match(style,/--accent:#006edb/);});
test('icona conversione usa doppia freccia simmetrica',()=>{const main=fs.readFileSync('src/main.js','utf8');assert.match(main,/M5 7h14/);assert.match(main,/M19 17H5/);assert.match(main,/m15 3 4 4-4 4/);assert.match(main,/m9 13-4 4 4 4/);});
test('workflow GitHub pubblica release stabile',()=>{const text=fs.readFileSync('.github/workflows/release.yml','utf8');assert.match(text,/Verify release versions/);assert.match(text,/package-lock\.json/);assert.match(text,/Cargo\.lock/);assert.match(text,/Read release description from tagged commit/);assert.match(text,/git log -1 --pretty=%b/);assert.match(text,/releaseBody:\s*\$\{\{ steps\.release_description\.outputs\.body \}\}/);assert.match(text,/prerelease:\s*false/);assert.match(text,/Build and publish release/);assert.doesNotMatch(text,/Stable release of _davCONVERT|generateReleaseNotes:\s*true/);});
test('set icone Tauri completo',()=>{for(const file of ['32x32.png','128x128.png','128x128@2x.png','app-icon.png','icon.ico','icon.icns'])assert.equal(fs.existsSync(`src-tauri/icons/${file}`),true,`${file} mancante`);});
test('metadata pacchetto _davstudios presenti',()=>{const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));const tauri=JSON.parse(fs.readFileSync('src-tauri/tauri.conf.json','utf8'));const cargo=fs.readFileSync('src-tauri/Cargo.toml','utf8');assert.equal(pkg.author,'_davstudios');assert.equal(pkg.license,'MIT');assert.equal(pkg.homepage,'https://davstudios.it');assert.equal(tauri.identifier,'studio.dav.convert');assert.equal(tauri.bundle.publisher,'_davstudios');assert.equal(tauri.bundle.homepage,'https://davstudios.it');assert.equal(tauri.bundle.license,'MIT');assert.equal(tauri.bundle.licenseFile,'../LICENSE');assert.equal(tauri.bundle.linux.deb.section,'utils');assert.equal(tauri.bundle.linux.deb.priority,'optional');assert.match(cargo,/license = "MIT"/);assert.match(cargo,/homepage = "https:\/\/davstudios\.it"/);});
test('motion system matches the _davstudios website v52 language',()=>{const motion=fs.readFileSync('src/motion.css','utf8');assert.match(motion,/--motion-duration-base:720ms/);assert.match(motion,/--motion-duration-slow:940ms/);assert.match(motion,/--motion-step:72ms/);assert.match(motion,/--motion-page-out:170ms/);assert.match(motion,/--motion-page-in:430ms/);assert.match(motion,/cubic-bezier\(\.16,1,\.3,1\)/);assert.match(motion,/blur\(3px\)/);assert.match(motion,/dav-theme-reveal 680ms/);assert.match(motion,/prefers-reduced-motion:reduce/);const main=fs.readFileSync('src/main.js','utf8');assert.match(main,/navigatePage/);assert.match(main,/is-page-leaving/);});
test('Windows release usa GUI subsystem e il reveal non apre una console',()=>{const main=fs.readFileSync('src-tauri/src/main.rs','utf8');const lib=fs.readFileSync('src-tauri/src/lib.rs','utf8');assert.match(main,/cfg_attr\(not\(debug_assertions\), windows_subsystem = "windows"\)/);assert.match(lib,/Command::new\("explorer"\)/);assert.match(lib,/creation_flags\(CREATE_NO_WINDOW\)/);});
test('README stabile e supporto _davstudios aggiornato',()=>{const readme=fs.readFileSync('README.md','utf8');assert.match(readme,/Offrimi Un Caffè/);assert.match(readme,/Local-first/);assert.match(readme,/Windows GUI subsystem/);assert.doesNotMatch(readme,/Current version:|\*\*v26\.10\.3/);for(const asset of ['website-it.svg','website-en.svg','buy-coffee-it.svg','buy-coffee-en.svg'])assert.equal(fs.existsSync(`.github/assets/${asset}`),true,`${asset} mancante`);});
